export const INDUSTRIES = [
  { id: 'salon', label: 'Salon' },
  { id: 'barbershop', label: 'Barbershop' },
  { id: 'spa', label: 'Spa' },
  { id: 'nail_salon', label: 'Nail Salon' },
  { id: 'auto_repair', label: 'Auto Repair' },
  { id: 'auto_body', label: 'Auto Body' },
  { id: 'medical_general', label: 'Medical (General)' },
  { id: 'medical_imaging', label: 'Medical Imaging' },
  { id: 'dental', label: 'Dental' },
  { id: 'chiropractic', label: 'Chiropractic' },
  { id: 'physical_therapy', label: 'Physical Therapy' },
  { id: 'massage', label: 'Massage' },
  { id: 'legal', label: 'Legal' },
  { id: 'plumbing', label: 'Plumbing' },
  { id: 'electrical', label: 'Electrical' },
  { id: 'hvac', label: 'HVAC' },
  { id: 'cleaning', label: 'Cleaning' },
  { id: 'landscaping', label: 'Landscaping' },
  { id: 'tattoo', label: 'Tattoo' },
  { id: 'photography', label: 'Photography' },
  { id: 'tutoring', label: 'Tutoring' },
  { id: 'pet_grooming', label: 'Pet Grooming' },
] as const;
